# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license = "MIT" # Replace with your chosen license. Options include MIT, GPL, etc.

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/yourusername/singleslotchest/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "singleslotchest" #mandatory

# The version number of the mod
version = "1.0.0" #mandatory

# A display name for the mod
displayName = "Single Slot Chest Mod" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
updateJSONURL="https://github.com/yourusername/singleslotchest/releases/latest" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/yourusername/singleslotchest" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional (place your logo in `src/main/resources`)

# A text field displayed in the mod UI
credits="Thanks to Forge and Minecraft Modding Community!" #optional

# A text field displayed in the mod UI
authors = "Your Name or Team Name" #optional

# Display Test controls the display for your mod in the server connection screen
displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description = '''This mod adds a custom block called Single Slot Chest, which provides a unique storage solution with a single slot.'''

# Dependencies - Forge and Minecraft are mandatory dependencies.
[[dependencies."singleslotchest"]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory (Ensure compatibility with Forge 47.x)
ordering = "NONE"
side = "BOTH"

[[dependencies."singleslotchest"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)" # Replace with your target Minecraft version range.
ordering = "NONE"
side = "BOTH"
